### ISSUE TITLE
Add strict mode to runtime-rest-client and runtime-lifecycle

### ISSUE THREAD

**Issue by hrajchert** [input-output-hk/marlowe-ts-sdk#166]
As mentioned in this [discussion response](https://github.com/input-output-hk/marlowe-ts-sdk/discussions/144#discussioncomment-8004831):

> We use the runtime types to validate external values that comes from the REST client, as a sanity check. But we don't use them from the user facing API as it would add some unwanted overhead. This means that if you are using the SDK with JS and you call runtimeLifecycle.contracts.createContract with a wrong contract or role token configuration, the SDK will manipulate or pass along the wrong values to the backend, yielding an unexpected error. I was thinking of adding a strict property when you create a runtime lifecycle to do this validation at the surface, maybe this can inprove the DX for JS users.

The idea is to modify `mkRestClient` and `mkRuntimeLifecycle` to accept a `strict` property that has `false` as the default value.

When the property is true, all calls to those API will try the guard on the input and throw a specific error (InvalidInputs/BadCall/error-to-be-named).

We could take this opportunity to also make a breaking change in the restClient so all functions accept a single object parameter. Right now we have some functions that accept a single Request parameter and some functions that accept multiple ones, this would simplify the API.

**Comment by bjornkihlberg** [comment]
We shouldn't have strict mode be `false` by default, it should be `true` by default. Otherwise it's one more thing a new developer using either JavaScript or poorly typed TypeScript will have to know about to get their code working well.

**Comment by bjornkihlberg** [comment]
# Notes

## Progress

- [x] Locate `mkRestClient`
- [ ] Locate `mkRuntimeLifecycle`
  - There are four definitions, which one?
